import { db } from "./firebase";
import {
    collection,
    getDocs,
    getDoc,
    doc,
    setDoc,
    updateDoc,
    deleteDoc,
    query,
    orderBy,
    Timestamp
} from "firebase/firestore";

export interface DevLog {
    id: string;
    title: string;
    content: string;
    tags: string[];
    status: 'Draft' | 'Published';
    publishedAt: any; // Firestore Timestamp
    // SEO / AEO metadata (optional, generated by AI)
    metaTitle?: string;
    metaDescription?: string;
    aeoKeywords?: string[];
}

const LOGS_COLLECTION = "logs";

/** Normalize publishedAt into a Date.
 *  Tolerates: Firestore Timestamp ({seconds}), ISO string (from Telegram bot),
 *  REST API format ({timestampValue}), or missing/invalid. */
export function toPublishedDate(publishedAt: any): Date | null {
    if (!publishedAt) return null;
    if (typeof publishedAt?.seconds === 'number') {
        return new Date(publishedAt.seconds * 1000);
    }
    if (typeof publishedAt?.toDate === 'function') {
        return publishedAt.toDate();
    }
    if (typeof publishedAt?.timestampValue === 'string') {
        const d = new Date(publishedAt.timestampValue);
        return isNaN(d.getTime()) ? null : d;
    }
    if (typeof publishedAt === 'string') {
        const d = new Date(publishedAt);
        return isNaN(d.getTime()) ? null : d;
    }
    return null;
}

export const logService = {
    async getAllLogs(includeDrafts = false): Promise<DevLog[]> {
        const q = query(collection(db, LOGS_COLLECTION), orderBy("publishedAt", "desc"));
        const querySnapshot = await getDocs(q);
        const logs = querySnapshot.docs.map(doc => doc.data() as DevLog);
        return includeDrafts ? logs : logs.filter(log => log.status === 'Published');
    },

    async saveLog(log: DevLog): Promise<void> {
        await setDoc(doc(db, LOGS_COLLECTION, log.id), {
            ...log,
            publishedAt: log.publishedAt || Timestamp.now()
        });
    },

    async getLog(logId: string): Promise<DevLog | null> {
        const docSnap = await getDoc(doc(db, LOGS_COLLECTION, logId));
        return docSnap.exists() ? docSnap.data() as DevLog : null;
    },

    async deleteLog(logId: string): Promise<void> {
        await deleteDoc(doc(db, LOGS_COLLECTION, logId));
    }
};
