import { db } from "./firebase";
import {
    collection,
    getDocs,
    getDoc,
    doc,
    setDoc,
    deleteDoc,
    query,
    orderBy,
    where,
    Timestamp
} from "firebase/firestore";

export type PublishedAtInput =
    | Timestamp
    | { seconds: number }
    | { toDate: () => Date }
    | { timestampValue: string }
    | string
    | null
    | undefined;

export interface DevLog {
    id: string;
    title: string;
    content: string;
    tags: string[];
    status: 'Draft' | 'Published';
    publishedAt: PublishedAtInput;
    // SEO / AEO metadata (optional, generated by AI)
    metaTitle?: string;
    metaDescription?: string;
    aeoKeywords?: string[];
}

const LOGS_COLLECTION = "logs";

/** Normalize publishedAt into a Date.
 *  Tolerates: Firestore Timestamp ({seconds}), ISO string (from Telegram bot),
 *  REST API format ({timestampValue}), or missing/invalid. */
export function toPublishedDate(publishedAt: PublishedAtInput): Date | null {
    if (!publishedAt) return null;
    if (typeof publishedAt === 'string') {
        const d = new Date(publishedAt);
        return isNaN(d.getTime()) ? null : d;
    }
    if (typeof publishedAt === 'object') {
        if ('seconds' in publishedAt && typeof publishedAt.seconds === 'number') {
            return new Date(publishedAt.seconds * 1000);
        }
        if ('toDate' in publishedAt && typeof publishedAt.toDate === 'function') {
            return publishedAt.toDate();
        }
        if ('timestampValue' in publishedAt && typeof publishedAt.timestampValue === 'string') {
            const d = new Date(publishedAt.timestampValue);
            return isNaN(d.getTime()) ? null : d;
        }
    }
    return null;
}

export const logService = {
    async getAllLogs(includeDrafts = false): Promise<DevLog[]> {
        // Public queries filter by status=='Published' to pass security rules.
        // where+orderBy on different fields would need a composite index, so
        // we sort client-side (dataset is small).
        // Admin panel sets includeDrafts=true and relies on the admin custom claim.
        const q = includeDrafts
            ? query(collection(db, LOGS_COLLECTION), orderBy("publishedAt", "desc"))
            : query(collection(db, LOGS_COLLECTION), where("status", "==", "Published"));
        const querySnapshot = await getDocs(q);
        const logs = querySnapshot.docs.map(doc => doc.data() as DevLog);
        if (includeDrafts) return logs;
        return logs.sort((a, b) => {
            const da = toPublishedDate(a.publishedAt)?.getTime() ?? 0;
            const db = toPublishedDate(b.publishedAt)?.getTime() ?? 0;
            return db - da;
        });
    },

    async saveLog(log: DevLog): Promise<void> {
        await setDoc(doc(db, LOGS_COLLECTION, log.id), {
            ...log,
            publishedAt: log.publishedAt || Timestamp.now()
        });
    },

    async getLog(logId: string): Promise<DevLog | null> {
        const docSnap = await getDoc(doc(db, LOGS_COLLECTION, logId));
        return docSnap.exists() ? docSnap.data() as DevLog : null;
    },

    async deleteLog(logId: string): Promise<void> {
        await deleteDoc(doc(db, LOGS_COLLECTION, logId));
    }
};
